// flow-typed signature: 5528e4bcd3bc4ce27bd399c13cace969
// flow-typed version: <<STUB>>/ignite-redux-logger_v^0.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-redux-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-redux-logger/patches' {
  declare module.exports: any;
}

declare module 'ignite-redux-logger/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-redux-logger/patches.js' {
  declare module.exports: $Exports<'ignite-redux-logger/patches'>;
}
declare module 'ignite-redux-logger/plugin.js' {
  declare module.exports: $Exports<'ignite-redux-logger/plugin'>;
}
