// flow-typed signature: 3a59b17fdf767f44c6bec6d2a56065e9
// flow-typed version: <<STUB>>/ignite-elements_v^0.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-elements/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-elements/plugin.js' {
  declare module.exports: $Exports<'ignite-elements/plugin'>;
}
