// flow-typed signature: 1b85461138a3b77db2daf28a405efe5c
// flow-typed version: <<STUB>>/reactotron-react-native_v^1.13.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-react-native/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-react-native/dist/index.js' {
  declare module.exports: $Exports<'reactotron-react-native/dist/index'>;
}
